services:
  code-space-test:
    build:
      context: ./apps/code-space/.
    ports:
      - 8022:22
      - 8080:8080

  hass-test:
    build:
      context: ./apps/home-assistant/.
      args:
        VERSION: 2024.7.2
    # environment:
    #   LD_LIBRARY_PATH: /usr/lib
