services:
  code-space-test:
    build:
      context: ./apps/code-space/.
    ports:
      - 8022:22
      - 8080:8080

  hass-test:
    build:
      context: ./apps/home-assistant/.
      args:
        VERSION: 2024.7.2
    # environment:
    #   LD_LIBRARY_PATH: /usr/lib

  vintagestory:
    build:
      context: ./apps/vintagestory/.
      args:
        VERSION: 1.20.11
    ports:
      - 42420:42420
    volumes:
      - "${PWD}/apps/vintagestory/mods.yaml:/init/mods.yaml:ro"

  comfyui:
    build:
      context: ./apps/comfyui/.
      args:
        VERSION: v0.3.62

  fluxgym:
    build:
      context: ./apps/fluxgym/.
      args:
        VERSION: 93c801d
    ports:
      - 7860:7860
      - 8080:8080

  renovate:
    image: renovate/renovate
    command:
      - "renovate"
      - "--platform=local"
    environment:
      LOG_LEVEL: debug
    working_dir: /renovate
    volumes:
      - ${PWD}:/renovate
